server:
  port: 8002

spring:
  application:
    name: mq-consumer

rocketmq:
  name-server: 139.198.19.125:9876
  consumer:
    group: mq-consumer-group

consumer:
  demo:
    topic: rmq-test-topic
    group: rmq-test-group
    group1: rmq-test-group-1


