server:
  port: 8002

spring:
  application:
    name: mq-consumer

rocketmq:
  name-server: 121.196.189.156:9876
  consumer:
    group: mq-consumer-group

consumer:
  demo:
    topic: rmq-test-topic
    group: rmq-test-group

