server:
  port: 8001

spring:
  application:
    name: mq-producer

rocketmq:
  # namesrv地址
  name-server: 139.198.19.125:9876
  # 生产者
  producer:
    # 组
    group: mq-producer-group
    # 发送超时
    send-message-timeout: 30000

producer:
  demo:
    topic: rmq-test-topic
